import '../../knowledge/models/engineering_entity.dart';
import '../../knowledge/models/evidence_link.dart';
import '../../knowledge/models/evidence_region.dart';
import '../../knowledge/models/knowledge_candidate.dart';
import '../../knowledge/models/knowledge_candidate_status.dart';
import '../../knowledge/services/knowledge_session_service.dart';
import '../models/ingestion_provenance.dart';
import '../models/ingestion_stage.dart';

/// The result of [CandidateGenerationService.generate]: everything needed
/// to populate an [IngestionResult]'s candidate-related fields.
class CandidateGenerationOutput {
  const CandidateGenerationOutput({
    required this.candidates,
    required this.evidenceRegions,
    required this.evidenceLinks,
    required this.candidateProvenance,
    required this.candidatePages,
  });

  final List<KnowledgeCandidate> candidates;
  final List<EvidenceRegion> evidenceRegions;
  final List<EvidenceLink> evidenceLinks;
  final Map<String, IngestionProvenance> candidateProvenance;

  /// Which source page each candidate's originating entity came from —
  /// handed to [RelationshipExtractionService] so it can restrict
  /// relationships to same-page pairs without re-deriving this from
  /// [evidenceRegions].
  final Map<String, int> candidatePages;
}

/// Turns extraction findings into Engineering Knowledge Candidates
/// (AP-INGEST-001 § 13/§ 17, WP-INGEST-001 § 13).
///
/// "Do not automatically commit candidates. Do not call repository
/// creation APIs from the candidate-generation stage." — this class never
/// imports `FoundationBridge`/`CommitTransactionService`/`CommitPlanService`,
/// and every [KnowledgeCandidate] it produces carries
/// `status: KnowledgeCandidateStatus.pending` and `committedObjectId: null`
/// — the `EXTRACTED`/`PENDING_REVIEW` lifecycle states AP-INGEST-001 § 17
/// requires, never `ACCEPTED`.
///
/// One candidate per [EngineeringEntity] — this is a *new*, automated
/// path onto the same [KnowledgeCandidate] model the existing manual
/// "engineer clicks Accept on an entity" workflow also produces (Work
/// Package 014's `EngineeringEntity.createdCandidateId`), not a
/// replacement for it: the source [EngineeringEntity] passed through here
/// is left completely untouched (still `EngineeringEntityStatus.pending`,
/// `createdCandidateId: null`) — that field's "accepted by an engineer"
/// semantics only ever change through the actual manual review workflow,
/// never through UIF's own automated extraction pass. The generated
/// candidate's own provenance (this class's [CandidateGenerationOutput.candidateProvenance])
/// is what lets a reviewer trace it back to the originating entity/run
/// instead.
abstract final class CandidateGenerationService {
  static CandidateGenerationOutput generate({
    required List<EngineeringEntity> entities,
    required String runId,
    required String vaultObjectId,
    required List<String> acquisitionRecordIds,
    required String pipelineVersion,
    required String parserId,
    required String parserVersion,
  }) {
    final candidates = <KnowledgeCandidate>[];
    final regions = <EvidenceRegion>[];
    final links = <EvidenceLink>[];
    final provenance = <String, IngestionProvenance>{};
    final pages = <String, int>{};
    final now = DateTime.now();

    for (final entity in entities) {
      final candidateId = KnowledgeSessionService.generateId('uif-candidate');
      final regionId = KnowledgeSessionService.generateId('uif-region');
      final linkId = KnowledgeSessionService.generateId('uif-link');

      candidates.add(
        KnowledgeCandidate(
          id: candidateId,
          type: entity.type.defaultCandidateType,
          name: entity.normalizedValue,
          description:
              'Extracted by the Universal Ingestion Framework from "${entity.extractedText}" on page ${entity.page}.',
          author: 'uif',
          status: KnowledgeCandidateStatus.pending,
          createdTime: now,
        ),
      );

      regions.add(
        EvidenceRegion(
          id: regionId,
          sourceId: entity.sourceId,
          page: entity.page,
          x: entity.boundingBox.x,
          y: entity.boundingBox.y,
          width: entity.boundingBox.width,
          height: entity.boundingBox.height,
          label: entity.type.label,
          notes: 'Auto-generated by UIF candidate generation from entity ${entity.id}.',
          createdTime: now,
        ),
      );

      links.add(EvidenceLink(id: linkId, candidateId: candidateId, regionId: regionId, createdTime: now));

      provenance[candidateId] = IngestionProvenance(
        vaultObjectId: vaultObjectId,
        acquisitionRecordIds: acquisitionRecordIds,
        runId: runId,
        stage: IngestionStage.candidateGeneration,
        processorId: 'uif.candidate_generation_service',
        processorVersion: '1.0.0',
        parserId: parserId,
        parserVersion: parserVersion,
        pipelineVersion: pipelineVersion,
        page: entity.page,
        sourceFingerprint: entity.sourceFingerprint,
      );

      pages[candidateId] = entity.page;
    }

    return CandidateGenerationOutput(
      candidates: candidates,
      evidenceRegions: regions,
      evidenceLinks: links,
      candidateProvenance: provenance,
      candidatePages: pages,
    );
  }
}
