import 'package:flutter/material.dart';

import '../../../core/theme/studio_colors.dart';

const _candidateCategories = [
  'Engineering Objects',
  'Relationships',
  'Equations',
  'Units',
  'Materials',
  'Symbols',
  'Behaviors',
  'Validation Rules',
  'Evidence',
];

/// Wizard Step 7 -- "Candidate Knowledge Preview."
///
/// **Honestly disclosed as out of this wizard's flow, not "not built."**
/// Candidate knowledge generation (OCR, entity extraction, relationship
/// candidates) is real and already implemented by the Universal
/// Ingestion Framework (WP-INGEST-004/005/006/007) -- but it runs as a
/// separate, explicit action ("Ingest into Knowledge Studio" on the
/// Reference Vault panel), not as an automatic continuation of this
/// wizard, because that action requires choosing a destination
/// Foundation Repository, which this wizard's own steps never collect.
/// Rather than fabricate example candidate objects here, or silently
/// re-run ingestion behind the engineer's back, this step honestly
/// tells the engineer where to go next, with every category shown
/// empty because none were generated by this wizard.
class WizardStepCandidatePreview extends StatelessWidget {
  const WizardStepCandidatePreview({super.key});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Candidate Knowledge Preview',
              style: TextStyle(color: StudioColors.textPrimary, fontSize: 16, fontWeight: FontWeight.w700)),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: StudioColors.warning.withValues(alpha: 0.1),
              border: Border.all(color: StudioColors.warning.withValues(alpha: 0.4)),
              borderRadius: BorderRadius.circular(6),
            ),
            child: const Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Icon(Icons.construction, size: 16, color: StudioColors.warning),
                SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'This wizard does not generate Candidate Engineering Objects automatically. Your artifact '
                    'is safely stored in the Reference Vault; to turn it into candidates (equations, materials, '
                    'symbols, behaviors...) via OCR and entity extraction, use "Ingest into Knowledge Studio" on '
                    'the Reference Vault panel -- it opens the real Universal Ingestion Framework and hands you '
                    'a Knowledge Session to review there.',
                    style: TextStyle(color: StudioColors.textPrimary, fontSize: 12, height: 1.4),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          for (final category in _candidateCategories)
            ExpansionTile(
              title: Text(category, style: const TextStyle(color: StudioColors.textPrimary, fontSize: 13)),
              subtitle: const Text('0 candidates', style: TextStyle(color: StudioColors.textDisabled, fontSize: 11)),
              children: const [
                Padding(
                  padding: EdgeInsets.fromLTRB(16, 0, 16, 12),
                  child: Align(
                    alignment: Alignment.centerLeft,
                    child: Text('Nothing extracted yet.', style: TextStyle(color: StudioColors.textDisabled, fontSize: 12)),
                  ),
                ),
              ],
            ),
        ],
      ),
    );
  }
}
