# CMake generated Testfile for 
# Source directory: /mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime
# Build directory: /mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/.scratch_build/wprep006/tests/runtime
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[oep_foundation_runtime_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/.scratch_build/wprep006/tests/runtime/oep_foundation_runtime_tests")
set_tests_properties([=[oep_foundation_runtime_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;3;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;0;")
add_test([=[oep_package_installation_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/.scratch_build/wprep006/tests/runtime/oep_package_installation_tests")
set_tests_properties([=[oep_package_installation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;7;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;0;")
add_test([=[oep_transaction_journal_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/.scratch_build/wprep006/tests/runtime/oep_transaction_journal_tests")
set_tests_properties([=[oep_transaction_journal_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;11;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;0;")
add_test([=[oep_trust_integration_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/.scratch_build/wprep006/tests/runtime/oep_trust_integration_tests")
set_tests_properties([=[oep_trust_integration_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;15;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.claude/worktrees/agent-a560bcb7977f8f129/tests/runtime/CMakeLists.txt;0;")
