#include "repository_generator.hpp"

#include <fstream>
#include <system_error>

#include "oep/repository/metadata.hpp"
#include "oep/repository/timestamp.hpp"
#include "oep/repository/uuid.hpp"
#include "foundation_version.hpp"

namespace oep::cli::generator {

namespace {

constexpr const char* kTemplateVersion = "1.0";

void write_file(const std::filesystem::path& path, const std::string& contents) {
    std::ofstream file(path, std::ios::binary);
    file << contents;
}

} // namespace

GenerationResult generate_foundation_repository(const std::filesystem::path& destination,
                                                 const std::string& repository_name) {
    std::error_code error_code;

    if (std::filesystem::exists(destination, error_code) &&
        !std::filesystem::is_empty(destination, error_code)) {
        return {false, "destination '" + destination.string() + "' already exists and is not empty"};
    }

    static constexpr const char* kSubdirectories[] = {
        "repository", "workspace", "packages", "cache", "logs", "exports", "settings"};

    for (const char* subdirectory : kSubdirectories) {
        std::filesystem::create_directories(destination / subdirectory, error_code);
        if (error_code) {
            return {false, "failed to create '" + std::string(subdirectory) + "': " + error_code.message()};
        }
    }

    write_file(destination / "README.md",
               "# " + repository_name + "\n\nAn Open Engineering Platform (OEP) repository.\n");

    write_file(destination / ".gitignore",
               "# Generated by OEP Foundation\n\ncache/\nlogs/\nexports/\n");

    oep::repository::RepositoryMetadata metadata;
    metadata.repository_id = oep::repository::generate_uuid_v4();
    metadata.repository_name = repository_name;
    metadata.repository_version = "1.0.0";
    metadata.foundation_version = kFoundationVersion;
    metadata.template_version = kTemplateVersion;
    metadata.created_utc = oep::repository::current_timestamp_utc();

    const oep::repository::SaveMetadataResult metadata_result =
        oep::repository::save_metadata(destination / "repository.json", metadata);
    if (!metadata_result.success) {
        return {false, metadata_result.error};
    }

    write_file(destination / "workspace.json",
               "{\n"
               "  \"defaultStudio\": null,\n"
               "  \"theme\": \"default\",\n"
               "  \"workspaceVersion\": \"" + std::string(kTemplateVersion) + "\"\n"
               "}\n");

    return {true, "created repository '" + repository_name + "' at " + destination.string()};
}

} // namespace oep::cli::generator
