# CMake generated Testfile for 
# Source directory: /mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine
# Build directory: /mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[oep_runtime_graph_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_runtime_graph_tests")
set_tests_properties([=[oep_runtime_graph_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;3;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_engineering_context_integration_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_engineering_context_integration_tests")
set_tests_properties([=[oep_engineering_context_integration_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;7;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_knowledge_graph_engine_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_knowledge_graph_engine_tests")
set_tests_properties([=[oep_knowledge_graph_engine_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;11;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_engineering_query_engine_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_engineering_query_engine_tests")
set_tests_properties([=[oep_engineering_query_engine_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;15;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_rules_engine_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_rules_engine_tests")
set_tests_properties([=[oep_rules_engine_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;19;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_validation_engine_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_validation_engine_tests")
set_tests_properties([=[oep_validation_engine_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;23;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_reasoning_engine_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_reasoning_engine_tests")
set_tests_properties([=[oep_reasoning_engine_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;27;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_engineering_intelligence_platform_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_engineering_intelligence_platform_tests")
set_tests_properties([=[oep_engineering_intelligence_platform_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;31;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
add_test([=[oep_end_to_end_workflow_tests]=] "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/.scratch_build/wprep006/tests/engine/oep_end_to_end_workflow_tests")
set_tests_properties([=[oep_end_to_end_workflow_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;35;add_test;/mnt/c/Users/david/OneDrive/Desktop/Projects/platform/oep_foundation/tests/engine/CMakeLists.txt;0;")
